### PR TITLE
add ios gitignore

### PR DESCRIPTION
**Pull request by antonelli**
@maxerogers @2020Deception @rehmatqadir 

Just grabbed one from a previous project. Anything we should add/change for a general project template?

### CODE REVIEW

**Comment by maxerogers** [comment]
Github ignores a new filetype .xcscmblueprint (added in Xcode 7)
`*.xcscmblueprint`

https://github.com/github/gitignore/blob/master/Objective-C.gitignore

**Comment by antonelli** [comment]
Good catch, I updated it with the latest github recommended ignores for xcode and osx

**Comment by BrandonRomano** [comment]
@maxerogers Can you check out @antonelli's change to make sure it resolves your comment -- would like to get this merged in!

**Comment by maxerogers** [comment]
looks good :+1:

**Comment by BrandonRomano** [comment]
Awesome, I am going to merge this in then.  Any additional changes feel free to open another PR!

**Pull request merged**
